name: Publish
on:
    pull_request:
        branches: [master]
        types: [closed]

jobs:
  release:
    if: contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    name: Bump version and Publish

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          always-auth: true
      
      - name: Install packages
        run: yarn install

      - name: Git config
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - run: yarn release
      - run: git push --follow-tags origin master
